### ISSUE TITLE
Test and document usage of mongodb authentication

### ISSUE THREAD

**Issue by asyd** [OpenCSI/lbe#20]

**Comment by asyd** [comment]
Also test sharding/replicats. Since mongodb clients must be aware of mongodb architecture, we need to ensure LBE is able to use more than one mongodb server

**Comment by cedj** [comment]
Added wiki tutorial for replicate part (https://github.com/OpenCSI/lbe/wiki/Replicate-Set-Mongo)

**Comment by cedj** [comment]
Added wiki tutorial for sharding part (https://github.com/OpenCSI/lbe/wiki/Sharding-mongo)
