### ISSUE TITLE
A group is not displayed in UI after import-target

### ISSUE THREAD

**Issue by asyd** [OpenCSI/lbe#45]
I create a group in the LDAP server, which follow the definition in LBE. After running import-target (where output show it found the group and created it in the backend), the UI doesn't display the group, while it exists in the backend:

`> db.groups.find()
{ "_id" : "Pink Floyd", "attributes" : { "uniqueMember" : [ "sbarrett", "dgilmour", "rwaters", "rwright" ], "cn" : [ "Pink Floyd" ] }, "changes" : { "set" : { "cn" : [ "Pink Floyd" ] }, "type" : -1 }, "created_at" : ISODate("2013-07-30T07:58:13Z"), "displayName" : "Pink Floyd", "status" : 0, "synced_at" : ISODate("2013-08-02T20:54:31.353Z"), "updated_at" : ISODate("2013-08-02T20:54:29.143Z") }
{ "_id" : "Queen", "status" : 0, "displayName" : "Queen", "synced_at" : ISODate("1970-01-01T00:00:00Z"), "attributes" : { "uniqueMember" : [ ], "cn" : [ "Queen" ] }, "created_at" : ISODate("2013-08-02T20:59:19Z"), "changes" : { "set" : { "uniqueMember" : [ ], "cn" : [ "Queen" ] }, "type" : -1 }, "updated_at" : ISODate("2013-08-02T20:59:19Z") }`

**Comment by cedj** [comment]
In order to "see" the imported group, you need to create its configuration using LBE (Group > Add group) by specifying its display name, object template & Script configuration file.
