### ISSUE TITLE
base dn hardcoded

### ISSUE THREAD

**Issue by pfautrero** [OpenCSI/lbe#52]
Hi,
Just want to import datas from my ldap server using :

python manage.py --import-target

Response gives me some strange hardcoded base dn (not in relation with one configured in /opt/lbe/lbe/settings.py) :
ou=Employees,ou=People,dc=opencsi,dc=com

base_dn methods from custom classes send back hardcoded strings.

Thanks

**Comment by asyd** [comment]
Le 27 août 2013 à 14:30, pfautrero notifications@github.com a écrit :

> Hi,
> Just want to import datas from my ldap server using :
> 
> python manage.py --import-target
> 
> Response gives me some strange hardcoded base dn (not in relation with one configured in /opt/lbe/lbe/settings.py) :
> ou=Employees,ou=People,dc=opencsi,dc=com
> 
> base_dn methods from custom classes send back hardcoded strings.

Hi, 

you also must modify custom/employee.py script, lbe/settings.py is only for authentication.

**Comment by pfautrero** [comment]
ok. Maybe it could be helpful to add such a config in your documentation :

https://github.com/OpenCSI/lbe/wiki/Initial%20configuration
