### ISSUE TITLE
page "manageacl" fails

### ISSUE THREAD

**Issue by pfautrero** [OpenCSI/lbe#53]
Hi,

If no ACL exist and if I try to reach http://server:8080/config/acl/manage/, server sends me back this error :

Error during template rendering

In template /opt/lbe/templates/config/acl/manage.html, error at line 9
Could not parse some characters: acl.group| ||default_if_none:""
1   {% extends "index.html" %}
2   {% block content %}
3   <h4>Manage ACL:</h4>
4   <table class="table">
5   <tr>
6   <td style="width:20%">Choose the ACL:</td>
7   <td><select
8   onChange="window.location.href=(window.location.pathname.substring(0,window.location.pathname.indexOf('manage/'))+'manage/'+$('select option:selected').val())">
9   {% for acl in aclList %}
10  <option value="{{ acl.id }}" {% if acl.id|stringformat:"s" == aclId %}
11  selected="selected" {% endif %}>{{ acl.object|default_if_none:"" }} {{ acl.group |default_if_none:"" }}:{{ acl.type }}</option> {% endfor %}
12  </select> <a href="#"
13  onClick="if($('select option:selected').text() && confirm('Do you want to remove the ACL instance?'))window.location.href = '/config/acl/remove/'+$('select option:selected').val();"
14  title="Remove ACL">
15  <span class='label label-important'>x</span></td>
16  </tr>
17  </table>
18  <form method="post" action="">{% csrf_token %}
19  {% include 'config/acl/form.html' %}

Thanks

**Comment by cedj** [comment]
Hi pfautrero,

thank you for the report.
Is the bug resolved now?

**Comment by pfautrero** [comment]
great, thanks.
